#!/bin/bash

LOG_FILE="/var/log/sshplus.log"

action="$1"
details="$2"

[[ -z "$action" ]] && exit 1
[[ -z "$details" ]] && details="-"

timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
host="$(hostname 2>/dev/null || echo unknown)"

echo "[$timestamp] [$host] [$action] $details" >> "$LOG_FILE"
exit 0
